### ISSUE TITLE
why you remove the BN from original resnet?

### ISSUE THREAD

**Issue by 646677064** [onkarganjewar/cmpe295-masters-project#3]
/mnt/storage/aa/cmpe295-masters-project-master/faster-rcnn-resnet/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in multiply
  pred_w = np.exp(dw) * widths[:, np.newaxis]
/mnt/storage/aa/cmpe295-masters-project-master/faster-rcnn-resnet/tools/../lib/fast_rcnn/bbox_transform.py:49: RuntimeWarning: overflow encountered in exp
  pred_h = np.exp(dh) * heights[:, np.newaxis]
/mnt/storage/aa/cmpe295-masters-project-master/faster-rcnn-resnet/tools/../lib/fast_rcnn/bbox_transform.py:49: RuntimeWarning: overflow encountered in multiply
  pred_h = np.exp(dh) * heights[:, np.newaxis]
/mnt/storage/aa/cmpe295-masters-project-master/faster-rcnn-resnet/tools/../lib/fast_rcnn/bbox_transform.py:46: RuntimeWarning: overflow encountered in multiply
  pred_ctr_x = dx * widths[:, np.newaxis] + ctr_x[:, np.newaxis]
/mnt/storage/aa/cmpe295-masters-project-master/faster-rcnn-resnet/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in multiply
  pred_ctr_y = dy * heights[:, np.newaxis] + ctr_y[:, np.newaxis]
/mnt/storage/aa/cmpe295-masters-project-master/faster-rcnn-resnet/tools/../lib/fast_rcnn/bbox_transform.py:53: RuntimeWarning: invalid value encountered in subtract
  pred_boxes[:, 0::4] = pred_ctr_x - 0.5 * pred_w
/mnt/storage/aa/cmpe295-masters-project-master/faster-rcnn-resnet/tools/../lib/fast_rcnn/bbox_transform.py:55: RuntimeWarning: invalid value encountered in subtract
  pred_boxes[:, 1::4] = pred_ctr_y - 0.5 * pred_h
/mnt/storage/aa/cmpe295-masters-project-master/faster-rcnn-resnet/tools/../lib/fast_rcnn/bbox_transform.py:57: RuntimeWarning: invalid value encountered in add
  pred_boxes[:, 2::4] = pred_ctr_x + 0.5 * pred_w
/mnt/storage/aa/cmpe295-masters-project-master/faster-rcnn-resnet/tools/../lib/fast_rcnn/bbox_transform.py:59: RuntimeWarning: invalid value encountered in add
  pred_boxes[:, 3::4] = pred_ctr_y + 0.5 * pred_h
/mnt/storage/aa/cmpe295-masters-project-master/faster-rcnn-resnet/tools/../lib/rpn/proposal_layer.py:175: RuntimeWarning: invalid value encountered in greater_equal
  keep = np.where((ws >= min_size) & (hs >= min_size))[0]
./experiments/scripts/2_ohem.sh: line 78: 36720 Floating point exception(core dumped) ./tools/train_net.py --gpu ${GPU_ID} --solver models/milkpowder/ResNet101_BN_SCALE_Merged/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/${NET}.v2.caffemodel --imdb ${TRAIN_IMDB} --iters ${ITERS} --cfg experiments/cfgs/faster_rcnn_end2end.yml ${EXTRA_ARGS}

**Comment by onkarganjewar** [comment]
I believe by removing the batchnorm layer from the current implementation of caffe reduces the memory usage, since it requires above 10G of memory in order to train ResNet-101. That's why the batchnorm layer's parameters are merged with Scale layer. Besides, by freezing BatchNorm + Scale layers and using the in-place eltwise sum with this [pull](https://github.com/BVLC/caffe/pull/3708), it gives much better performance even from the [original paper](https://github.com/KaimingHe/deep-residual-networks).

I think if you follow this [issue](https://github.com/rbgirshick/py-faster-rcnn/issues/122), you could probably get the detailed explanation of this. Also, see [here](https://github.com/Eniac-Xie/faster-rcnn-resnet/blob/master/tools/merge_bn_scale.py#L16).
